BoxConfigComponentBundle:
    resource: "@BoxConfigComponentBundle/Resources/config/routing.yml"
    prefix:   /component

BoxConfigBoxBundle:
    resource: "@BoxConfigBoxBundle/Resources/config/routing.yml"
    prefix:   /box

BoxConfigAccountBundle:
    resource: "@BoxConfigAccountBundle/Resources/config/routing.yml"
    prefix:   /

BoxConfigDefaultBundle:
    resource: "@BoxConfigDefaultBundle/Resources/config/routing.yml"
    prefix:   /
