parameters:

services:
    security.acl.object_identity_retrieval_strategy:
        class:     BoxConfig\DefaultBundle\Security\Acl\Domain\ObjectIdentityRetrievalStrategy
        public:    false
        arguments: [@doctrine.orm.entity_manager]
