component_hardware:
    pattern:  /
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:index" }

component_hardware_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:show" }

component_hardware_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:new" }

component_hardware_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:create" }
    requirements: { _method: post }

component_hardware_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:edit" }

component_hardware_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:update" }
    requirements: { _method: post }

component_hardware_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:delete" }
    requirements: { _method: post }

component_hardware_comment_new:
    pattern:  /{id}/comment/new
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:commentNew" }

component_hardware_comment_create:
    pattern:  /{id}/comment/create/
    defaults: { _controller: "BoxConfigComponentBundle:Hardware:commentCreate" }
    requirements: { _method: post }