component_operatingsystem:
    pattern:  /
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:index" }

component_operatingsystem_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:show" }

component_operatingsystem_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:new" }

component_operatingsystem_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:create" }
    requirements: { _method: post }

component_operatingsystem_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:edit" }

component_operatingsystem_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:update" }
    requirements: { _method: post }

component_operatingsystem_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigComponentBundle:OperatingSystem:delete" }
    requirements: { _method: post }
