component_software:
    pattern:  /
    defaults: { _controller: "BoxConfigComponentBundle:Software:index" }

component_software_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoxConfigComponentBundle:Software:show" }

component_software_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigComponentBundle:Software:new" }

component_software_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigComponentBundle:Software:create" }
    requirements: { _method: post }

component_software_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigComponentBundle:Software:edit" }

component_software_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigComponentBundle:Software:update" }
    requirements: { _method: post }

component_software_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigComponentBundle:Software:delete" }
    requirements: { _method: post }
