BoxConfigBoxBundle_machine:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/machine.yml"
    prefix:   /machine

BoxConfigBoxBundle_environment:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/environment.yml"
    prefix:   /machine/{machine_id}/environment

BoxConfigBoxBundle_software:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/software.yml"
    prefix:   /machine/{machine_id}/environment/{environment_id}/software