parameters:
#    box_config_box.example.class: BoxConfig\BoxBundle\Example

services:
    badge.twig.extension:
           class: BoxConfig\BoxBundle\Twig\badgeExtension
           tags:
                - { name: twig.extension }
