parameters:
#    box_config_component.example.class: BoxConfig\ComponentBundle\Example

services:
#    box_config_component.example:
#        class: %box_config_component.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
