environment:
    pattern:  /
    defaults: { _controller: "BoxConfigBoxBundle:Environment:index" }

environment_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigBoxBundle:Environment:new" }

environment_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigBoxBundle:Environment:create" }
    requirements: { _method: post }

environment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigBoxBundle:Environment:edit" }

environment_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigBoxBundle:Environment:update" }
    requirements: { _method: post }

environment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigBoxBundle:Environment:delete" }
    requirements: { _method: post }
