box_machine:
    pattern:  /
    defaults: { _controller: "BoxConfigBoxBundle:Machine:index" }

box_machine_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigBoxBundle:Machine:new" }

box_machine_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigBoxBundle:Machine:create" }
    requirements: { _method: post }

box_machine_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigBoxBundle:Machine:edit" }

box_machine_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigBoxBundle:Machine:update" }
    requirements: { _method: post }

box_machine_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigBoxBundle:Machine:delete" }
    requirements: { _method: post }
