box_software:
    pattern:  /
    defaults: { _controller: "BoxConfigBoxBundle:Software:index" }

box_software_ajax:
    pattern:  /ajax/{command}/{id}
    defaults: { _controller: "BoxConfigBoxBundle:Software:ajax" }
