<?php

namespace BoxConfig\BoxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends EntityRepository
{
}